### ISSUE TITLE
reading somefile.obj FAILED (80070002)

### ISSUE THREAD

**Issue by Postal86** [Microsoft/DirectXMesh#12]
Problem converting  from obj  files   into sdkmesh  i have tried  with  three object.

**Comment by walbourn** [comment]
What command-line exactly are you using?

The HRESULT (80070002) is ``ERROR_FILE_NOT_FOUND`` which means you probably don't have the right current working directory or you are not using the correct path to find the obj file.

See [the wiki](https://github.com/Microsoft/DirectXMesh/wiki/Meshconvert) as well.

**Comment by Postal86** [comment]
meshconvert  filename.obj -sdkmesh

![untitled1](https://cloud.githubusercontent.com/assets/15318234/13661436/1c3ba498-e6ac-11e5-9d78-3c46b476b5a2.png)
![untitled2](https://cloud.githubusercontent.com/assets/15318234/13661435/1c3b093e-e6ac-11e5-9bfc-7080c8599da3.png)

**Comment by walbourn** [comment]
The problem is that ``houseinterior.obj`` is not in the current directory, i.e. ``D:\VisualStudioProjects\DirectXMesh-master\Meshconvert\Bin\Desktop_2015\Win32\Debug`.

**Comment by Postal86** [comment]
What  u mean  current directory  ?!  meshconvert.exe  app and  object  file  are  located in the same directory  Chuck.  Look  at  the  screen  shot. 
![Uploading Untitled.png…]()

**Comment by Postal86** [comment]
![untitled](https://cloud.githubusercontent.com/assets/15318234/13695999/f2ce2762-e77c-11e5-83c7-884571242ff5.png)

**Comment by walbourn** [comment]
Can you attach your ``houseinterior.obj``? I suspect the problem is that your mtl file that matches it is missing.

**Comment by Postal86** [comment]
Cannot attach  zip  file  throwing  an error  i'll  send  you by  e-mail.

**Comment by walbourn** [comment]
# 3ds Max Wavefront OBJ Exporter v0.97b - (c)2007 guruware
    # File Created: 21.08.2015 18:38:02

    mtllib house interior.mtl


First, the filename is a little questionable here having a space in the middle. Second, as I noted before you don't have this mtl file in your current working directory.

**Comment by Postal86** [comment]
I found  that  file  in the Web as a  free  resource  3D  Objects(and  i did not know if mtl file was needed )  , just  wanted geometry for my  demo.  Oh  couldn't  imagine material file was missing  and that's why  converter  was  throwing an error. file name  i know , when  i  was converting  i have skipped  that space, but  i  think mtl file is missing  for the object  and  that's  why  during reading error  was  throwing.   Thnks Chuck.
