### ISSUE TITLE
meshconvert.exe Windows 10 Crash

### ISSUE THREAD

**Issue by JrIndie** [Microsoft/DirectXMesh#21]
Hello, while using the meshconverter(downloaded it yesterday), it seems to be crashing after it starts reading a *.fbx file.  The *.fbx file I am using is attached.

Tested (crash on read):
meshconvert TestScene.fbx -cmo -nodds -flipz -y
meshconvert TestScene.fbx -n -op

[Assets.zip](https://github.com/Microsoft/DirectXMesh/files/1609814/Assets.zip)

Thanks for any of your help.

**Comment by walbourn** [comment]
Thanks for the report. I've improved the error handling/messages here.

The ``meshconvert`` tool does not support Autodesk FBX files. It can read from [Wavefront OBJ](https://en.wikipedia.org/wiki/Wavefront_.obj_file) files. If you want to convert ``FBX`` files, take a look at [Samples Content Exporter from the legacy DirectX SDK](https://github.com/walbourn/contentexporter).
