### ISSUE TITLE
MSVC conformance mode build failure in WaveFrontReader

### ISSUE THREAD

**Issue by aymarino** [Microsoft/DirectXMesh#29]
We build DirectXMesh as part of MSVC rolling regression tests, and with the latest compiler toolset we found this source issue under the C++ standards conformance mode "/permissive-".

```
wavefrontreader.h(555): error C3861: 'XMFLOAT3': identifier not found
        BoundingBox::CreateFromPoints(bounds, vertices.size(), reinterpret_cast<const XMFLOAT3*>(vertices.data()), sizeof(Vertex));
                                                                                      ^
```

The issue is that the type `XMFLOAT3`, and the type `BoundingBox`, are defined in the DirectX namespace, where lookup cannot find them from the template definition. Unlike other functions in this class, `LoadVBO` doesn't have a local `using namespace DirectX;` declaration. If you add that, lookup succeeds.

This failure doesn't appear in the non-conformant default mode likely because a using directive for the DirectX namespace appears before the template is instantiated, so lookup succeeds in the instantiation context.

**Comment by walbourn** [comment]
Thanks. Fixed with [this commit](https://github.com/Microsoft/DirectXMesh/commit/9f0b4e3591e528f09eb454681297d7bf22e2ee9a).
