### ISSUE TITLE
C# compatibility

### ISSUE THREAD

**Issue by BMarques** [microsoft/DirectXMesh#41]
Hello,
Would it be possible to either have a C API or COM API so that it's possible to write a c# wrapper for this? I've successfully created a DirectX c# wrapper that works with UWP, but I'm definitely missing these tools, such as directxmesh or directxtex to speed up development (CMO models, DDS texture compatibility for instance).

Thank you.

**Comment by walbourn** [comment]
Someone has written some wrappers already at least for [DirectXTex](https://www.nuget.org/packages/DirectXTexNet/). You could contact them to see if they can do another for DirectXMesh.
