### ISSUE TITLE
FAILED (80070002) when converting a .obj to skdmesh

### ISSUE THREAD

**Issue by RyanWilliams99** [microsoft/DirectXMesh#55]
I'm using the following commands I have also tried with various arguments but still no luck.

`meshconvert monkey.obj`
and
`meshconvert monkey.obj -sdkmesh`

[monkey.zip](https://github.com/microsoft/DirectXMesh/files/6190849/monkey.zip)

**Comment by walbourn** [comment]
The error result ``80070002`` is ``ERROR_FILE_NOT_FOUND``--the VS Error Lookup tool is handy here.

If you open the ``monkey.obj`` file in text editor, you'll see that it references a different filename for the ``mtl`` file than you expect:

```
mtllib monkey2k.mtl
```

Rename your ``monkey.mtl`` to ``monkey2k.mtl``.
