### ISSUE TITLE
Mouse movement is very jerky at higher sensitivities

### ISSUE THREAD

**Issue by jkinz3** [microsoft/DirectXMesh#59]
Just putting the raw mouse deltas in is fine but often isn't fast enough. Scaling the deltas makes the mouse movement incredibly jerky when the mouse is moving diagonally, which seems to be a symptom of the deltas being stored as integers. If this is intended, is there a way to smooth out the movement and increase the sensitivity?

**Comment by walbourn** [comment]
This issue is not related to DirectXMesh. It's been moved to [DirectX Tool Kit](https://github.com/microsoft/DirectXTK/issues/267).
