### ISSUE TITLE
Setup for building with MinGW unclear

### ISSUE THREAD

**Issue by infinitesnow** [microsoft/DirectXMesh#70]
I can see the project is supposed to build with MinGW. I have setup an [MSYS2](https://www.msys2.org/) environment, but I don't seem to be able to understand the setup required to build.

I see from the CMake config file that the project depends on [Directx-Headers](https://github.com/microsoft/DirectX-Headers) and [DirectxMath](https://github.com/microsoft/DirectXMath), which I have cloned in a folder accessible by MSYS2. However, I can't build Directx-Headers; it seems MSYS2 is using its own includes instead of the Windows SDK ones, which miss some required macros. I opened a separate issue about this, but I assume I'm opening an issue here in case I am missing something obvious.

**Comment by infinitesnow** [comment]
I managed to build using Cmake + ninja + Clang + MinGW, disabling the test and googletest targets in the DirectX headers project, installing it, and pointing DirectXMesh to it.

I used the same line for all three (headers, math, mesh) projects:
```
cmake -G "Ninja" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS="-v -target x86_64-pc-windows-gnu" -DCMAKE_C_FLAGS="-v -target x86_64-pc-windows-gnu" -DDXHEADERS_BUILD_GOOGLE_TEST=n -DDXHEADERS_BUILD_TEST=n -DCMAKE_INSTALL_PREFIX=".\install" -DCMAKE_PREFIX_PATH="C:\Users\<uname>\dxmesh\DirectX-Headers\build\install;C:\Users\<uname>\dxmesh\DirectXMath\build\install"
```

**Comment by walbourn** [comment]
These projects all have CMakePresets "x64-Debug-MinGW", although I'm using [vcpkg](https://github.com/microsoft/vcpkg/) for dependencies.

The MinGW version of the Windows headers is a hodge-podge of stuff from WINE, and in many cases the headers they ship aren't actually usable at all. That's why it needs DirectX-Headers and DirectXMath to build.
